/* 
Write a function that returns "rock, paper, or scissors" from the computer.
    Define function named getComputerChoice.
        Define a variable "element" that stores a number generated by the Math.random method.
        Create a conditional statement that returns rock if Math.random returns a value that is greater than 0 and less than or equal to 0.33.
            Elseif Math.random returns a value that is greater than 0.33 and less than or equal to 0.66, return paper.
            Else if any other value is returned, return scissors.
    */

function getComputerChoice() {
    let element = Math.random();
    if (element >= 0 && element <= 0.33) { 
        return "rock";
    } else if (element > 0.33 && element <= 0.66) {
       return "paper";
    } else {
        return "scissors";
    }
}
// console.log(getComputerChoice());

/* 
Write a function that returns "rock, paper or scissors" from the human.
    Define a function named getHumanChoice.
        Define a variable "element" that stores user input from a promt that says, "Type rock, paper, or scissors".
        Return the lower case of the user input.
*/

function getHumanChoice() {
    let element = prompt("Type rock, paper or scissors")
    if (element.toLowerCase() == "rock") {
        return "rock";
    } else if (element.toLowerCase() == "paper") {
        return "paper";
    } else if (element.toLowerCase() == "scissors") {
        return "scissors";
    } 
}

// console.log(getHumanChoice());

/* 
Declare the players score variables.
    Create variable named humanScore with an initial value of 0.
    Create variable named computerScore with an initial value of 0.
*/

let humanScore = 0;
let computerScore = 0;

/*
Write the logic to play a single round. 
    Create a function named playRound.
        Define 2 parameters: humanChoice and computerChoice.
        Ensure that humanChoice is case-insensitive.
        Create conditional statement. If hC is rock and cC is rock, 
        return with console log "Draw! Computer chose rock. Rock and rock smash each other".
        Else if hC is rock and cC is paper, 
        return with console log "You lose! Computer chose paper. Paper wraps rock".
        Increment computerScore by 1.
        Else if hC is rock and cC is scissors, 
        return with console log "You win! Computer chose scissors. Rock smashes scissors". 
        Increment humanScore by 1.
        Else if hC is paper and cC is rock, 
        return with console log, "You win! Computer chose rock. Paper wraps rock".
        Increment humanScore by 1.
        Else if hC is paper and cC is paper,
        return with console log, "Draw! Computer chose paper. Paper and paper wrap each other".
        Else if hC is paper and cC is scissors,
        return with console log, "You lose! Computer chose scissors. Scissors cuts paper".
        Increment computerScore by 1.
        Else if hC is scissors and cC is rock,
        return with console log, "You lose! Computer chose rock. Rock smashes scissors".
        Increment computerScore by 1.
        Else if hC is scissors and cC is paper,
        return with console log, "You win! Computer chose paper. Scissors cuts paper".
        Increment humanScore by 1.
        Else if hC is scissors and cC is scissors, 
        return with console log, "Draw! Scissors are having trouble cutting eachother".
        Else return with console log, "Wrong user input".
    
    Create a variable named humanSelection that invokes the getHumanChoice function.
    Create a variable named computerSelection that invokes the getComputerChoice function. 
    Invoke the playRound function, using humanSelection and computerSelection as arguments. 
*/

/*

function playRound(humanChoice, computerChoice) {
    humanChoice = humanChoice.toLowerCase();
    if (humanChoice == "rock" && computerChoice == "rock") {
        console.log("Draw! Computer chose rock. Rock and rock smash each other");
    } else if (humanChoice == "rock" && computerChoice == "paper") {
        console.log("You lose!Computer chose paper. Paper wraps rock");
        computerScore++;
    } else if (humanChoice == "rock" && computerChoice == "scissors") {
        console.log("You win! Computer chose scissors. Rock smashes scissors");
        humanScore++;
    } else if (humanChoice == "paper" && computerChoice == "rock") {
        console.log("You win! Computer chose rock. Paper wraps rock");
        humanScore++;
    } else if (humanChoice == "paper" && computerChoice == "paper") {
        console.log("Draw! Computer chose paper. Paper and paper wrap each other")
    } else if (humanChoice == "paper" && computerChoice == "scissors") {
        console.log("You lose! Computer chose scissors. Scissors cuts paper");
        computerScore++;
    } else if (humanChoice == "scissors" && computerChoice == "rock") {
        console.log("You lose! Computer chose rock. Rock smashes scissors");
        computerScore++;
    } else if (humanChoice == "scissors" && computerChoice == "paper") {
        console.log("You win! Computer chose paper. Scissors cuts paper");
        humanScore++;
    } else if (humanChoice == "scissors" && computerChoice == "scissors") {
        console.log("Draw! Scissors are having trouble cutting eachother");
    } else console.log("Wrong user input")
}

humanSelection = getHumanChoice();
computerSelection = getComputerChoice();
playRound(humanSelection, computerSelection);
console.log(humanScore);
console.log(computerScore);

*/

/* 
Write logic to play the entire game.
    Create a function named playGame.
        Create a play round function like above. 
        Create a variable named humanSelection that invokes the getHumanChoice function.
        Create a variable named computerSelection that invokes the getComputerChoice function. 
        Invoke the playRound function, using humanSelection and computerSelection as arguments 5 times.
        After each round print "Your Score: humanScore" and "Computer Score: computerScore".
        If humanScore > computerScore print "You win the game!"
        Else, "You lost the game!"
*/

function playGame() {

    // Declare playRound function

    function playRound(humanChoice, computerChoice) {
        humanChoice = humanChoice.toLowerCase();
        if (humanChoice == "rock" && computerChoice == "rock") {
            console.log("Draw! Computer chose rock. Rock and rock smash each other");
        } else if (humanChoice == "rock" && computerChoice == "paper") {
            console.log("You lose!Computer chose paper. Paper wraps rock");
            computerScore++;
        } else if (humanChoice == "rock" && computerChoice == "scissors") {
            console.log("You win! Computer chose scissors. Rock smashes scissors");
            humanScore++;
        } else if (humanChoice == "paper" && computerChoice == "rock") {
            console.log("You win! Computer chose rock. Paper wraps rock");
            humanScore++;
        } else if (humanChoice == "paper" && computerChoice == "paper") {
            console.log("Draw! Computer chose paper. Paper and paper wrap each other")
        } else if (humanChoice == "paper" && computerChoice == "scissors") {
            console.log("You lose! Computer chose scissors. Scissors cuts paper");
            computerScore++;
        } else if (humanChoice == "scissors" && computerChoice == "rock") {
            console.log("You lose! Computer chose rock. Rock smashes scissors");
            computerScore++;
        } else if (humanChoice == "scissors" && computerChoice == "paper") {
            console.log("You win! Computer chose paper. Scissors cuts paper");
            humanScore++;
        } else if (humanChoice == "scissors" && computerChoice == "scissors") {
            console.log("Draw! Scissors are having trouble cutting eachother");
        } else console.log("Wrong user input")
    }

    // Invoke playRound function 5 times and print the score after each round. 
    // Declare humanSelection and computerSelection variables at start of each round.
    // Round 1

    humanSelection = getHumanChoice();
    computerSelection = getComputerChoice();
    playRound(humanSelection, computerSelection);
    console.log("Human Score: " + humanScore); 
    console.log("Computer Score: " + computerScore);

    // Round 2

    humanSelection = getHumanChoice();
    computerSelection = getComputerChoice();
    playRound(humanSelection, computerSelection);
    console.log("Human Score: " + humanScore); 
    console.log("Computer Score: " + computerScore);

    // Round 3

    humanSelection = getHumanChoice();
    computerSelection = getComputerChoice();
    playRound(humanSelection, computerSelection);
    console.log("Human Score: " + humanScore); 
    console.log("Computer Score: " + computerScore);

    // Round 4

    humanSelection = getHumanChoice();
    computerSelection = getComputerChoice();
    playRound(humanSelection, computerSelection);
    console.log("Human Score: " + humanScore); 
    console.log("Computer Score: " + computerScore);

    // Round 5

    humanSelection = getHumanChoice();
    computerSelection = getComputerChoice();
    playRound(humanSelection, computerSelection);
    console.log("Human Score: " + humanScore); 
    console.log("Computer Score: " + computerScore);

    // Declare if the use wins or lost the game 
}

playGame()