/* 
Write a function that returns "rock, paper, or scissors" from the computer.
    Define function named getComputerChoice.
        Define a variable "element" that stores a number generated by the Math.random method.
        Create a conditional statement that returns rock if Math.random returns a value that is greater than 0 and less than or equal to 0.33.
            Elseif Math.random returns a value that is greater than 0.33 and less than or equal to 0.66, return paper.
            Else if any other value is returned, return scissors.
    */

function getComputerChoice() {
    let element = Math.random();
    if (element >= 0 && element <= 0.33) { 
        return "rock";
    } else if (element > 0.33 && element <= 0.66) {
       return "paper";
    } else {
        return "scissors";
    }
}
console.log(getComputerChoice());

/* 
Write a function that returns "rock, paper or scissors" from the human.
    Define a function named getHumanChoice.
        Define a variable "element" that stores user input from a promt that says, "Type rock, paper, or scissors".
        Return the lower case of the user input.
*/

function getHumanChoice() {
    let element = prompt("Type rock, paper or scissors")
    if (element.toLowerCase() == "rock") {
        return "rock"
    } else if (element.toLowerCase() == "paper") {
        return "paper"
    } else if (element.toLowerCase() == "scissors") {
        return "scissors"
    }
}

console.log(getHumanChoice());